### ISSUE TITLE
simtrace2-cardem integration code?

### ISSUE THREAD

**Issue by laf0rge** [tomasz-lisowski/swsim#1]
Hi @tomasz-lisowski - just stumbled across your project.

You mentioned that you used the swsim with simtrace2-cardem - great! However, I was unable to find the related code so far.

Did you publish it?  I think it would be rather useful to have this around. Thanks!

**Comment by tomasz-lisowski** [comment]
You'll need the [swICC software card reader](https://github.com/tomasz-lisowski/swicc-drv-ifd). It allows swSIM (and any other [swICC](https://github.com/tomasz-lisowski/swicc)-based card) to appear as a regular PC/SC card. Then it's enough to run the stock SIMtrace host software (`simtrace2-cardem-pcsc`) with the correct PC/SC card ID and USB path to the SIMtrace device.

**Comment by laf0rge** [comment]
Ah, ok, you did it that way. 

Somehow I mistakenly thought you had directly integrated with / linked against libosmo-simtrace2. Nevermind.
