### ISSUE TITLE
incorrect code for UPDATE BINARY command

### ISSUE THREAD

**Issue by edbek** [tomasz-lisowski/swsim#10]
https://github.com/tomasz-lisowski/swsim/blob/ed2cd4b661b3aa9be0c9e884cb12eacecfbbb103/src/apduh.c#L1208

As I understand it should be:

 memcpy(&file_edit->data[offset], cmd->data->b, 
                           cmd->data->len);

**Comment by tomasz-lisowski** [comment]
Thanks once again! Really appreciate your help, and sorry for this fairly obvious bug.
