### ISSUE TITLE
 to register in the 4G LTE network

### ISSUE THREAD

**Issue by edbek** [tomasz-lisowski/swsim#12]
Is it possible to use SWSIM to register in the 4G LTE network? What authentication algorithms are used for this then?

**Comment by tomasz-lisowski** [comment]
I just committed b376096, so authentication should just work out of the box. Enjoy!

**Comment by edbek** [comment]
Thank you, Tomasz!
And with these new algorithms, have you managed to enter the 4G network in practice? Or does this need to be checked?

**Comment by tomasz-lisowski** [comment]
I tested it on an srsRAN 4G network. So it should work as long as you have all the necessary key material and milenage configuration of the network. Just make sure to input all that information in here (current values are just placeholders I used in testing): https://github.com/tomasz-lisowski/swsim/blob/b376096285c5bd1878b3d4d5247c5925b4fb4fb2/src/swsim.c#L15-L42

**Comment by edbek** [comment]
Not quite clear. Is one Milenage algorithm enough for authentication in 4G? Or are there more additional algorithms in srsRAN on top of Milenage?
As far as I know, Milenage is used only for 2G, 3G networks.

**Comment by edbek** [comment]
Tomasz, can I write to you by email regarding cooperation?

**Comment by tomasz-lisowski** [comment]
Sure, you can find my email on my GitHub profile https://github.com/tomasz-lisowski

As for Milenage, it is actually used in 3G, 4G, and 5G. Have a look at this https://arxiv.org/abs/2107.07416v1 it contains clear diagrams of how the authentication works in each network generation. As you'll see, the only change between each generation is the work that needs to be done by the UE and network.
