### ISSUE TITLE
Compile error on using docker

### ISSUE THREAD

**Issue by 54shady** [tomasz-lisowski/swsim#17]
what would be the reason for the error below, while using the defualt docker build script
I try to build the code on my host, get the same error message

i double check the file :lib/make-pal/pal.mak, which is exist

make[1]: Entering directory '/opt/swsim/lib/swicc'
Makefile:2: lib/make-pal/pal.mak: No such file or directory
make[1]: *** No rule to make target 'lib/make-pal/pal.mak'.  Stop.
make[1]: Leaving directory '/opt/swsim/lib/swicc'
make: *** [Makefile:110: clean] Error 2

**Comment by tomasz-lisowski** [comment]
You probably forgot to clone the repo recursively, so submodules are missing (i.e. directories inside `lib/` are empty).

**Comment by 54shady** [comment]
i already sync the submodule and download the file

[swsim (main)]$ git submodule init
[swsim (main)]$ git submodule update
[swsim (main)]$ git submodule sync
Synchronizing submodule url for 'lib/make-pal'
Synchronizing submodule url for 'lib/swicc'
Synchronizing submodule url for 'lib/tau'
[swsim (main)]$ git submodule status
 ddfd124643d39b3399f09e9441a3028f3f3cc175 lib/make-pal (heads/master)
 6955a1906864d808e77bf01661f17bfc3c0b5c62 lib/swicc (heads/main)
 95448f36bbba808ce58bbed8d81f4644f0371647 lib/tau (v1.0.0-201-g95448f3)

in the lib directory as below, the lib are not empty

[swsim (main)]$ tree  lib/
lib/
├── make-pal
│   ├── LICENSE
│   ├── pal.mak
│   └── README.md
├── swicc
│   ├── doc
│   │   └── install.md
│   ├── dockerfile
│   ├── docker.sh
│   ├── include
│   │   └── swicc
│   │       ├── apdu.h
│   │       ├── apduh.h
│   │       ├── apdu_rc.h
│   │       ├── atr.h
│   │       ├── common.h

**Comment by tomasz-lisowski** [comment]
It appears that while you initialized direct submodules of swSIM, the submodules of the dependency swICC were not initialized.

Could you confirm that directories in `lib/swicc/lib/` are not empty?

**Comment by mariusmue** [comment]
To add to @tomasz-lisowski prior comment:

To initialize and update all submodules recursively, you can execute:

```bash
git submodule update --init --recursive
```

It appears from the posted command that you only got the submodules for swsim itself.

**Comment by 54shady** [comment]
[swsim (main)]$ git submodule update --init --recursive
Cloning into '/home/zeroway/github/swsim/lib/swicc/lib/tau'...
Submodule path 'lib/swicc/lib/cjson': checked out 'b45f48e600671feade0b6bd65d1c69de7899f2be'
Submodule path 'lib/swicc/lib/tau': checked out 'bde87091a5d9f8730da808785072323194ec4b3c'

the directory lib/swicc/lib is not empty
  [swsim (main)]$ tree lib/swicc/lib/ | wc -l
  329

still, can not compile the code
[swsim (main)]$ ./docker.sh
#0 building with "default" instance using docker driver

......
#6 exporting to image
#6 exporting layers done
#6 writing image sha256:fe23fb020cf0b4455e16be3a9fc61a709c6b716a67e1a84b5da4fc96fbbdb09f done
#6 naming to docker.io/tomasz-lisowski/swsim:1.0.0 done
#6 DONE 0.0s
rm -rf build
cd lib/swicc && make clean
make[1]: Entering directory '/opt/swsim/lib/swicc'
Makefile:2: lib/make-pal/pal.mak: No such file or directory
make[1]: *** No rule to make target 'lib/make-pal/pal.mak'.  Stop.
make[1]: Leaving directory '/opt/swsim/lib/swicc'
make: *** [Makefile:110: clean] Error 2

**Comment by 54shady** [comment]
I reclone the whole repo to fix the issue.
